version: "3"

services:
    nats-server:
      container_name: nats-server
      image: nats-server:v1
      restart: always
      build: ./server
      ports: 
        - "4222:4222"
      volumes:
        - ./server:/go/src/nats
      networks: 
        - NATS
    nats-sub:
      container_name: nats-sub
      image: nats-sub:v1
      restart: always
      build: ./sub
      volumes: 
        - ./sub:/go/src/nats
      networks: 
        - NATS
    nats-pub:
      container_name: nats-pub
      image: nats-pub:v1
      restart: always
      build: ./pub
      ports:
        - "5000:5000"
      volumes: 
        - ./pub:/go/src/nats
      networks: 
        - NATS

networks: 
  NATS:
    driver: "bridge"