version: "3"

services: 
  rabbitmq:
    image: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks: 
      - rabbitmqs
    
  publicador:
    build: ./Publicador
    restart: on-failure
    ports: 
      - "3500:3500"
    depends_on: 
      - rabbitmq
    networks: 
      - rabbitmqs
  
  consumidor:
    build: ./Consumidor
    restart: on-failure
    depends_on: 
      - rabbitmq
    networks: 
      - rabbitmqs

networks: 
    rabbitmqs:
      driver: "bridge"